# python3 installer.py
import os, time, sys

os.system('clear')
os.system('apt update -y &&  apt upgrade -y') 
os.system('apt install nodejs -y')
os.system('apt install npm -y')
os.system('apt install python3 -y')
os.system('apt install python3-pip -y')
os.system('user-agents')
os.system('colors')
os.system('hpack')
os.system('axios')
os.system('cheerio')
os.system('node-fetch')
os.system('gradient-string')
os.system('fake-useragent')
os.system('header-generator')
os.system('readline-sync')
os.system('npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth async puppeteer-extra-plugin-adblocker')
os.system(' apt update -y &&  apt install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils -y')
os.system('net fs url hpack path colors child_process http2 random-referer request axios tls crypto header-generator user-agents cluster fake-useragent randomstring string-random puppeteer puppeteer-extra puppeteer-extra-plugin-stealth async hpack')
os.system('hpack node-fetch node-fetch@2 socks dns colors')
os.system('random-useragent')
os.system('pip install colorama request')
time.sleep(1)
os.system('clear')
time.sleep(5)
print("Buka File Module.txt dan salin text itu dan paste ke vps agar mendownload sisa module yang di perlukan")
time.sleep(7)
sys.exit()